### ISSUE TITLE
Dependency (winston) breaks on node 14.x

### ISSUE THREAD

**Issue by gitbugr** [apostrophecms/apostrophe-cli#35]
Winston 2.x doesn't work with node 14.x. and thus breaks this tool.

https://github.com/winstonjs/winston/issues/1797

```
 Apostrophe  create-project  Failed
(node:75963) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object.exports.setLevels (/Users/kyron/.nvm/versions/node/v14.4.0/lib/node_modules/apostrophe-cli/node_modules/winston/lib/winston/common.js:32:14)
    at Object.<anonymous> (/Users/kyron/.nvm/versions/node/v14.4.0/lib/node_modules/apostrophe-cli/node_modules/winston/lib/winston.js:83:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
```

For now I've downgraded my node version to 13.x and it's working fine.

**Comment by DABH** [comment]
winston 2.4.5 has been released which should resolve this issue, though we encourage migrating to Winston@3 which is maintained and is tested with latest Node versions.

**Comment by abea** [comment]
Thanks for flagging this. We have a 3.x version that's inching closer to being approved that updates `prompt`, getting rid of `winston` entirely. https://github.com/apostrophecms/apostrophe-cli/pull/32/files

It might be possible to update the current version's `prompt` dependency as well, which would be a great contribution.

**Comment by abea** [comment]
The 3.x version stalled out while we work on Apostrophe 3.x, so we're fixing this. Sorry for the delay!
